spring:
  redis:
    host: localhost
    port: 6379
  mvc:
    throw-exception-if-no-handler-found: true
  activemq:
    broker-url: tcp://localhost:61616
xmpp:
  api:
    users: '/users'
    chatRooms: '/chatrooms'
    messages: '/messages/users'
    groups: '/groups'
    group: '/group'
  groups:
    member: 'normal'
    agent: 'agent'
    admin: 'admin'
  ip: '127.0.0.1'
  domain: 'openfirelocal.com'
  secret: 'ueXm49NFTHv7785B'
  user:
    username: 'notification'
    password: '123456'
    nickname: '系统通知'
  rest:
    port: '9090'
    prefix: '/plugins/restapi/v1'